services:
  - type: web
    name: collapp-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        value: c7570490f2bc60ffba82d3fae48dc91b8bec7c0323ac804bf5487b4c1bf084bd
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ENCRYPTION_KEY
        value: collapp-encryption-key-2024-secure
      - key: DATABASE_URL
        fromDatabase:
          name: collapp-db
          property: connectionString
      - key: DATABASE_URL_ASYNC
        fromDatabase:
          name: collapp-db
          property: connectionString

  - type: pserv
    name: collapp-db
    env: postgresql
    plan: free
    databaseName: collapp_db
    databaseUser: collapp_user