"""Add AI tables

Revision ID: 002
Revises: 001
Create Date: 2024-01-01 00:01:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_a_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_b_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('match_percent', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('collab_suggestions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_a_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_b_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('plataforma', sa.String(), nullable=False),
    sa.Column('frase_inicial_chat', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('media_kits',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('profile_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_kits')
    op.drop_table('collab_suggestions')
    op.drop_table('matches')
    # ### end Alembic commands ###